config/routes.rb
# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  root 'searches#index'
  get "pages/home"
  post "contacts", to: "pages#contact", as: :contact
  get "search", to: "pages#search", as: :search
  post "enable_analytics", to: "analytics#enable", as: :enable_analytics
  delete "clear_history", to: "analytics#clear_history", as: :clear_history
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :visitor
  end
  

app/models/event.rb
class Event < ApplicationRecord
  serialize :params
  belongs_to :visitor

  def self.page_views
    select(:path)
      .where(method: "GET")
      .group(:path)
      .count
  end

  def self.unique_page_views
    select(:path)
      .from(
        Event
          .select(:path, :visitor_id)
          .distinct
          .where(method: "GET")
          .group(:path, :visitor_id)
      )
      .group(:path)
      .count(:path)
  end
end

app/models/search.rb
class Search < ApplicationRecord
  belongs_to :visitor
end

app/models/user.rb
class User < ApplicationRecord
  has_many :visits, class_name: "Visitor"
  has_many :events, through: :visits

  def time_on_site
    Visitor.total_time_on_site_for_visitor(visits)
  end

  def average_time_on_site
    Visitor.average_time_on_site_for_visitor(visits)
  end
end

app/models/visitor.rb
class Visitor < ApplicationRecord
  belongs_to :user, optional: true
  has_many :events
  has_many :searches

  scope :time_on_site_for_visitor, ->(visitor) {
    select("lower_bounds, upper_bounds")
      .from(
        Event
        .select(
          "visitor_id,
          MIN(created_at) AS lower_bounds,
          MAX(created_at) AS upper_bounds"
        )
        .where(visitor: visitor)
        .group(:visitor_id)
      )
  }

  def self.time_on_site
    select("visitor_id, lower_bounds, upper_bounds")
      .from(
        Event
          .select(
            "visitor_id,
            MIN(created_at) AS lower_bounds,
            MAX(created_at) AS upper_bounds"
          )
          .group(:visitor_id)
      )
      .pluck(
        "visitor_id",
        Arel.sql("EXTRACT(EPOCH FROM (upper_bounds - lower_bounds))")
      )
      .sort
  end

  def self.total_time_on_site_for_visitor(visitor)
    time_on_site_for_visitor(visitor).sum(
      Arel.sql("EXTRACT(EPOCH FROM (upper_bounds - lower_bounds))")
    )
  end

  def self.average_time_on_site_for_visitor(visitor)
    time_on_site_for_visitor(visitor).average(
      Arel.sql("EXTRACT(EPOCH FROM (upper_bounds - lower_bounds))")
    )
  end

  def self.delete_all_older_than(timestamp)
    destroy_by("created_at < ?", timestamp)
  end
end

app/controllers/analytics_controller.rb
class AnalyticsController < ApplicationController
    def enable
      session[:enable_analytics] = true
  
      redirect_to root_path, notice: "You have enabled your session to be tracked."
    end
  
    def clear_history
      @user = User.last
      @user.visits.destroy_all
  
      redirect_to root_path, notice: "History deleted."
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # Ensure that the visitor is tracked for every request
    include SetCurrentVisitor

    before_action :turbo_frame_request_variant
    
    private
  
    def turbo_frame_request_variant
      request.variant = :turbo_frame if turbo_frame_request?
    end
end

app/controllers/concerns/set_current_visitor.rb
# Logic to set current visitor 
module SetCurrentVisitor    
  extend ActiveSupport::Concern

  included do
    before_action :set_current_visitor, if: :should_set_current_visitor?
  end

  private

  def create_current_visitor
    visitor = Visitor.create!(
      user_agent: request.user_agent
    )
    session[:visitor_id] = visitor.id

    visitor
  end

  def set_current_visitor
    Current.visitor ||= Visitor.find_by(id: session[:visitor_id]) || create_current_visitor
  end

  def should_set_current_visitor?
    session[:enable_analytics] == true
  end
end

app/controllers/concerns/track_event.rb
# Track event for visitor
module TrackEvent    
  extend ActiveSupport::Concern

  def track_event
    if session[:enable_analytics] == true
      CreateEventJob.perform_later(
        visitor: Current.visitor,
        path: request.path,
        method: request.method,
        params: filter_sensitive_data(event_params)
      )
    end
  end

  private

  def filter_sensitive_data(params)
    return if params.nil?

    ActiveSupport::ParameterFilter.new(
      Rails.application.config.filter_parameters
    ).filter(params)
  end

  def event_params
    request.query_parameters.presence || request.request_parameters.presence
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController  
  include TrackEvent

  before_action :track_event

  def contact
  end

  def home
  end

  def search
  end

  def sign_in
    @user = User.find_by!(email: params[:user][:email])
    Current.visitor.presence && Current.visitor.update!(user: @user)

    redirect_to root_path
  end

  def sign_up
    @user = User.create!(params.require(:user).permit(:email))
    Current.visitor.presence && Current.visitor.update!(user: @user)

    redirect_to root_path
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  include TrackEvent

  before_action :track_event

  def index

    if params[:query].present?
      @searches = Search.where("input LIKE ?", "%#{params[:query]}%")
 
        @search = Search.new(input: params[:query], visitor_id: session[:visitor_id])
        @search.save
    
    else
      @searches = Search.all
    end

    if turbo_frame_request?
      render partial: "searches", locals: { searches: @searches }
    else
      render "index"
    end
  end

  def create
    @search = Search.new(search_params)
    @search.save
    redirect_to root_path
  end

  private

  def search_params
    params.require(:search).permit(:input, :visitor_id).whith_defaults(visitor_id: session[:visitor_id])
  end
end

app/helpers/analytics_helper.rb
module AnalyticsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SearchEngine</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <% if session[:enable_analytics] == true %>
    <%= yield %>
  <% end %>
  <% unless session[:enable_analytics] == true %>
      <%= button_to "Enable analytics", enable_analytics_path %>
  <% end %>
  </body>
</html>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/search.html.erb
<h1>Pages#search</h1>
<p>Find me in app/views/pages/search.html.erb</p>

app/views/searches/_search.html.erb
<div id="<%= dom_id search %>">
  <p>
    <%= search.input %>
  </p>
</div>

app/views/searches/_searches.html.erb
<%= turbo_frame_tag "searches" do %>
  <%= render searches %>
<% end %>

app/views/searches/index.html+turbo_frame.erb
<%= turbo_frame_tag "searches" do %>
  <%= render @searches %>
<% end %>

app/views/searches/index.html.erb
<%= form_with(url: root_path, method: "GET", data: { controller: "form-submission", turbo_frame: "searches", turbo_action: "advance" }) do |form| %>
    <%= form.label :query, "Search here : " %>
    <%= form.text_field :query, data: { action: "input->form-submission#search" } %>
    <%= form.submit "Search", name: nil %>
<% end %>

<%= render "searches", searches: @searches %>